on:
  push:
    branches: main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      pull-requests: write # Required to add comment and label.
      id-token: write     # Required to create a comment with the plan output.
      issues: write       # Requ
    env:
      ARM_CLIENT_ID: 2a3adff6-1144-4784-81ee-b7e0c02a4ded
      ARM_SUBSCRIPTION_ID: 382b6330-6cf0-4e15-b202-543c02240501
      ARM_TENANT_ID: 153f1179-3606-40e1-8c1b-e328b9987f3e
      ARM_USE_OID: true

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Run plan by default, or apply on merge.
      - uses: op5dev/tf-via-pr@v13
        with:
          working-directory: terraform
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
          arg-lock: ${{ github.event_name == 'push' }}
          arg-backend-config: dev.tfbackend
          arg-var-file: dev.tfvars